# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main-menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from widgets.Button132x64 import Button132x64

class UI_MainMenu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background-color: #D9EEF6;")
        
        #start button
        self.startBtn = Button132x64(self.centralwidget)
        self.startBtn.setGeometry(QtCore.QRect(400, 60, 132, 64))
        self.startBtn.setName("startBtn")
        self.startBtn.setImage("images/start-button.png")
        self.startBtn.clicked.connect(self.handleClickStart)
        
        #settings button
        self.settingsBtn = Button132x64(self.centralwidget)
        self.settingsBtn.setGeometry(QtCore.QRect(400, 150, 132, 64))
        self.settingsBtn.setName("settingsBtn")
        self.settingsBtn.setImage("images/settings-button.png")
        self.settingsBtn.clicked.connect(self.handleClickSettings)
        
        #tutorial button
        self.tutorialBtn = Button132x64(self.centralwidget)
        self.tutorialBtn.setGeometry(QtCore.QRect(400, 240, 132, 64))
        self.tutorialBtn.setName("tutorialBtn")
        self.tutorialBtn.setImage("images/tutorial-button.png")
        self.tutorialBtn.clicked.connect(self.handleClickTutorial)
        
        #exit button
        self.exitBtn = Button132x64(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(400, 330, 132, 64))
        self.exitBtn.setName("exitBtn")
        self.exitBtn.setImage("images/exit-button.png")
        self.exitBtn.clicked.connect(self.handleClickExit)
        
        #bar
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        
    def handleClickStart(self):
        print("Clicked Start Button")
        
    def handleClickSettings(self):
        print("Clicked Settings Button")
        
    def handleClickTutorial(self):
        print("Clicked Tutorial Button")
        
    def handleClickExit(self):
        MainWindow.close()
   
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UI_MainMenu()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
