# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main-menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton

url = "D:/HCMUS/Internetworking/Project/Lab1 - Socket Programming/who-want-to-be-a-millionare/gui/"

class MainMenuButton(QPushButton):
    mouseHover = QtCore.pyqtSignal(bool)

    def __init__(self, parent=None):
        QPushButton.__init__(self, parent)
        self.setEnabled(True)
        self.setMouseTracking(True)
        self.setStyleSheet("border: none;")
        self.setAutoFillBackground(False)
        
    def setName(self, name):
        self.setObjectName(name)
        
    def setImage(self, path):
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(url + path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setIcon(icon)
        self.setIconSize(QtCore.QSize(132, 64))

    def enterEvent(self, event):
        self.mouseHover.emit(True)
        self.setIconSize(QtCore.QSize(120, 60))

    def leaveEvent(self, event):
        self.mouseHover.emit(False)
        self.setIconSize(QtCore.QSize(132, 64))

class UI_MainMenu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background-color: #D9EEF6;")
        
        #start button
        self.startBtn = MainMenuButton(self.centralwidget)
        self.startBtn.setGeometry(QtCore.QRect(250, 220, 132, 64))
        self.startBtn.setName("startBtn")
        self.startBtn.setImage("images/start-btn.png")
        self.startBtn.clicked.connect(self.handleClickStart)
        
        #settings button
        self.settingsBtn = MainMenuButton(self.centralwidget)
        self.settingsBtn.setGeometry(QtCore.QRect(250, 310, 132, 64))
        self.settingsBtn.setName("settingsBtn")
        self.settingsBtn.setImage("images/settings-btn.png")
        self.settingsBtn.clicked.connect(self.handleClickSettings)
        
        #bar
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        
    def handleClickStart(self):
        print("Clicked Start Button")
        
    def handleClickSettings(self):
        print("Clicked Settings Button")
   
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UI_MainMenu()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
