# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QGroupBox, QPushButton
from widgets.Button64x64 import Button64x64
url = "D:/HCMUS/Internetworking/Project/Lab1 - Socket Programming/who-want-to-be-a-millionare/gui/"
        
class BackButton(QPushButton):
    mouseHover = QtCore.pyqtSignal(bool)

    def __init__(self, parent=None):
        QPushButton.__init__(self, parent)
        self.setEnabled(True)
        self.setMouseTracking(True)
        self.setStyleSheet("border: none;")
        self.setAutoFillBackground(False)
        self.setObjectName("BackBtn")
        self.setImage("images/back-btn.png")
        self.setStyleSheet(''' border: none; 
                               border-radius: 0px;
                               background-color: transparent;  ''')
        
    def setImage(self, path):
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(url + path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setIcon(icon)
        self.setIconSize(QtCore.QSize(25, 25))

    def enterEvent(self, event):
        self.mouseHover.emit(True)
        self.setIconSize(QtCore.QSize(23, 23))

    def leaveEvent(self, event):
        self.mouseHover.emit(False)
        self.setIconSize(QtCore.QSize(25, 25))
        
class Dialog(QGroupBox):
    def __init__(self, parent = None):
        QGroupBox.__init__(self, parent)
        self.resize(200, 110)
        self.move(220, 150)
        self.setStyleSheet(''' border: 2px solid #FBC02D; 
                               border-radius: 10px; 
                               background-color: white;''')
        self.initUI()

    def initUI(self):
        #message
        self.text = QtWidgets.QTextBrowser(self)
        self.text.setStyleSheet(''' border: none; 
                                    border-radius: 0px;
                                    background-color: transparent; 
                                    padding: 5px;
                                    font-weight: bold;
                                    color: #C58F09;''')
        self.text.resize(200, 70)
        
        #button
        self.btn = BackButton(self)
        self.btn.resize(25, 25)
        self.btn.move(90, 70)
        self.btn.clicked.connect(self.handleBackButton)
        
    def setMessage(self, message):
        self.text.setText(message)
        
    def handleBackButton(self):
        self.hide()
        

class UI_RegisterScreen(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background-color: #D9EEF6;")
        
        #dialog
        self.dialog = Dialog(self.centralwidget)
        self.dialog.hide()
        
        #text label
        self.textLabel = QtWidgets.QLabel(self.centralwidget)
        self.textLabel.setGeometry(QtCore.QRect(120, 160, 400, 25))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.textLabel.setFont(font)
        self.textLabel.setStyleSheet("color: #1F566D;")
        self.textLabel.setObjectName("textLabel")
        
        #input name
        self.inputName = QtWidgets.QLineEdit(self.centralwidget)
        self.inputName.setGeometry(QtCore.QRect(110, 190, 421, 41))
        self.inputName.setAutoFillBackground(False)
        self.inputName.setStyleSheet('''border: 1px solid #1F566D; 
                                        border-radius: 20px; 
                                        background-color: white; 
                                        padding-left: 10px;
                                        padding-right: 10px;
                                        font-size: 12px;
                                        text-transform: uppercase;
                                        font-weight: bold;
                                        color: #1F566D;''')
        self.inputName.setObjectName("inputName")
        
        #OK Button
        self.OKBtn = Button64x64(self.centralwidget)
        self.OKBtn.setName("OKBtn")
        self.OKBtn.setImage("images/OK-btn.png")
        self.OKBtn.move(QtCore.QPoint(290, 250))
        self.OKBtn.clicked.connect(self.handleSubmitUsername)
        
        #setup
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textLabel.setText(_translate("MainWindow", "ENTER YOUR USERNAME"))
        
    def handleSubmitUsername(self):
        username = self.inputName.text()
        print(username)
        #check username
        self.dialog.setMessage("Username has been already registered. \nPlease choose another one")
        self.dialog.show()
        self.dialog.activateWindow()
        self.dialog.raise_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UI_RegisterScreen()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
