# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from gui.widgets.Button100x100 import Button100x100
from gui.widgets.RankingTable import RankingTable
import os

url = os.path.dirname("./gui/")

class UI_EndgameScreen(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 960)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        #sself.centralwidget.setStyleSheet("background-color: #D9EEF6;")
        
        #title
        self.titleInformation = QtWidgets.QLabel(self.centralwidget)
        self.titleInformation.setGeometry(QtCore.QRect(0, 50, 1280, 100))
        self.titleInformation.setText("")
        self.titleInformation.setPixmap(QtGui.QPixmap(os.path.join(url, "images/leader-board.png")))
        self.titleInformation.setAlignment(QtCore.Qt.AlignCenter)
        self.titleInformation.setObjectName("titleInformation")
        
        #restart button
        self.restartBtn = Button100x100(self.centralwidget)
        self.restartBtn.setName("restartBtn")
        self.restartBtn.setImage("images/back-btn.png")
        self.restartBtn.move(QtCore.QPoint(500, 750))
        
        #exitBtn
        self.exitBtn = Button100x100(self.centralwidget)
        self.exitBtn.setName("exitBtn")
        self.exitBtn.setImage("images/exit-btn.png")
        self.exitBtn.move(QtCore.QPoint(700, 750))
        self.exitBtn.clicked.connect(lambda: self.handleClickExit(MainWindow))
        
        #table
        self.rankingTable = RankingTable(self.centralwidget)
        self.rankingTable.createHeading()
        self.rankingTable.setValue([['1', 'Nhi', '100'], ['2', 'Tan', '50'], ['3', 'Nhan', '0']])
        
        #setup
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        
    def handleClickExit(self, MainWindow):
        MainWindow.close()
