# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from gui.widgets.Button100x100 import Button100x100

url = "./who-want-to-be-a-millionare/gui/"

class UI_InformationScreen(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 960)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        #self.centralwidget.setStyleSheet("background-color: #D9EEF6;")
        
        #title
        self.titleInformation = QtWidgets.QLabel(self.centralwidget)
        self.titleInformation.setGeometry(QtCore.QRect(0, 150, 1280, 100))
        self.titleInformation.setText("")
        self.titleInformation.setPixmap(QtGui.QPixmap(url + "images/match-information.png"))
        self.titleInformation.setAlignment(QtCore.Qt.AlignCenter)
        self.titleInformation.setObjectName("titleInformation")
        
        #label
        self.numOfQuestions = QtWidgets.QLabel(self.centralwidget)
        self.numOfQuestions.setGeometry(QtCore.QRect(300, 300, 396, 48))
        self.numOfQuestions.setText("")
        self.numOfQuestions.setPixmap(QtGui.QPixmap(url + "images/num-question.png"))
        self.numOfQuestions.setScaledContents(True)
        self.numOfQuestions.setObjectName("numOfQuestions")
        self.numOfPlayers = QtWidgets.QLabel(self.centralwidget)
        self.numOfPlayers.setGeometry(QtCore.QRect(300, 400, 352, 48))
        self.numOfPlayers.setText("")
        self.numOfPlayers.setPixmap(QtGui.QPixmap(url + "images/num-player.png"))
        self.numOfPlayers.setScaledContents(True)
        self.numOfPlayers.setObjectName("numOfPlayers")
        self.playerOrder = QtWidgets.QLabel(self.centralwidget)
        self.playerOrder.setGeometry(QtCore.QRect(300, 500, 204, 47))
        self.playerOrder.setText("")
        self.playerOrder.setPixmap(QtGui.QPixmap(url + "images/order.png"))
        self.playerOrder.setScaledContents(True)
        self.playerOrder.setObjectName("playerOrder")
        
        #input
        self.inputQuestion = QtWidgets.QLabel(self.centralwidget)
        self.inputQuestion.setGeometry(QtCore.QRect(900, 300, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.inputQuestion.setFont(font)
        self.inputQuestion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inputQuestion.setStyleSheet("color: #FBC02D; ")
        self.inputQuestion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputQuestion.setObjectName("inputQuestion")
        
        self.inputPlayer = QtWidgets.QLabel(self.centralwidget)
        self.inputPlayer.setGeometry(QtCore.QRect(900, 400, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.inputPlayer.setFont(font)
        self.inputPlayer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inputPlayer.setStyleSheet("color: #FBC02D; ")
        self.inputPlayer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputPlayer.setObjectName("inputPlayer")
        
        self.inputOrder = QtWidgets.QLabel(self.centralwidget)
        self.inputOrder.setGeometry(QtCore.QRect(900, 500, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.inputOrder.setFont(font)
        self.inputOrder.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inputOrder.setStyleSheet("color: #FBC02D; ")
        self.inputOrder.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputOrder.setObjectName("inputOrder")
        
        #play button
        self.playBtn = Button100x100(self.centralwidget)
        self.playBtn.setImage("images/play-btn.png")
        self.playBtn.move(590, 600)
        self.playBtn.setName("playBtn")
        self.playBtn.clicked.connect(self.handleClickPlayButton)
        
        #setup
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inputQuestion.setText(_translate("MainWindow", "0"))
        self.inputPlayer.setText(_translate("MainWindow", "0"))
        self.inputOrder.setText(_translate("MainWindow", "0"))
        
    def inputNumber(self, question, player, order):
        self.inputQuestion.setText(str(question))
        self.inputPlayer.setText(str(player))
        self.inputOrder.setText(str(order))
        
    def handleClickPlayButton(self):
        print("Clicked!")
        #move to waiting screen --> play

