# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main-menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets, QtGui
from gui.widgets.Button248x64 import Button248x64

class UI_MainMenu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 960)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background-color: #D9EEF6;")
        
        #game-name
        self.gameName = QtWidgets.QLabel(self.centralwidget)
        self.gameName.setGeometry(QtCore.QRect(0, -100, 1280, 800))
        self.gameName.setText("")
        pixmap = QtGui.QPixmap("./who-want-to-be-a-millionare/gui/images/game-name.png")
        pixmap = pixmap.scaledToWidth(900)
        self.gameName.setPixmap(pixmap)
        self.gameName.setAlignment(QtCore.Qt.AlignCenter)
        self.gameName.setObjectName("titleInformation")
        
        #start button
        self.startBtn = Button248x64(self.centralwidget)
        self.startBtn.setGeometry(QtCore.QRect(280, 550, 248, 64))
        self.startBtn.setName("startBtn")
        self.startBtn.setImage("images/start-button.png")
        self.startBtn.clicked.connect(self.handleClickStart)
        
        #settings button
        self.settingsBtn = Button248x64(self.centralwidget)
        self.settingsBtn.setGeometry(QtCore.QRect(750, 550, 248, 64))
        self.settingsBtn.setName("settingsBtn")
        self.settingsBtn.setImage("images/settings-button.png")
        self.settingsBtn.clicked.connect(self.handleClickSettings)
        
        #tutorial button
        self.tutorialBtn = Button248x64(self.centralwidget)
        self.tutorialBtn.setGeometry(QtCore.QRect(280, 680, 248, 64))
        self.tutorialBtn.setName("tutorialBtn")
        self.tutorialBtn.setImage("images/tutorial-button.png")
        self.tutorialBtn.clicked.connect(self.handleClickTutorial)
        
        #exit button
        self.exitBtn = Button248x64(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(750, 680, 248, 64))
        self.exitBtn.setName("exitBtn")
        self.exitBtn.setImage("images/exit-button.png")
        self.exitBtn.clicked.connect(lambda: self.handleClickExit(MainWindow))
        
       #setup
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        
    def handleClickStart(self):
        print("Clicked Start Button")
        
    def handleClickSettings(self):
        print("Clicked Settings Button")
        
    def handleClickTutorial(self):
        print("Clicked Tutorial Button")
        
    def handleClickExit(self, MainWindow):
        MainWindow.close()
   
