# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from gui.widgets.Button100x100 import Button100x100
from gui.widgets.DialogFailUsername import DialogFailUsername
from server.utils.username import checkUsername
import gui.screen

class UI_RegisterScreen(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 960)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        #self.centralwidget.setStyleSheet("background-color: #D9EEF6;")
        
        #dialog
        self.dialog = DialogFailUsername(self.centralwidget)
        self.dialog.hide()
        
        #text label
        self.textLabel = QtWidgets.QLabel(self.centralwidget)
        self.textLabel.setGeometry(QtCore.QRect(240, 310, 400, 25))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.textLabel.setFont(font)
        self.textLabel.setStyleSheet("color: #1F566D;")
        self.textLabel.setObjectName("textLabel")
        
        #input name
        self.inputName = QtWidgets.QLineEdit(self.centralwidget)
        self.inputName.setGeometry(QtCore.QRect(225, 350, 800, 50))
        self.inputName.setAutoFillBackground(False)
        self.inputName.setStyleSheet('''border: 1px solid #1F566D; 
                                        border-radius: 20px; 
                                        background-color: white; 
                                        padding-left: 10px;
                                        padding-right: 10px;
                                        font-size: 16px;
                                        font-weight: bold;
                                        color: #1F566D;''')
        self.inputName.setObjectName("inputName")
        
        #OK Button
        self.OKBtn = Button100x100(self.centralwidget)
        self.OKBtn.setName("OKBtn")
        self.OKBtn.setImage("images/OK-btn.png")
        self.OKBtn.move(QtCore.QPoint(590, 450))
        self.OKBtn.clicked.connect(lambda: self.handleSubmitUsername(MainWindow))
        
        #setup
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textLabel.setText(_translate("MainWindow", "ENTER YOUR USERNAME"))
        
    def handleSubmitUsername(self, MainWindow):
        username = self.inputName.text()
        #check username
        err = checkUsername(name=username)
        if err != None:
            self.dialog.setMessage(err)
            self.dialog.show()
            self.dialog.activateWindow()
            self.dialog.raise_()

        else:
            #ui = gui.screen.UI_LoadingScreen()
            ui = gui.screen.UI_QuestionScreen()
            ui.setupUi(MainWindow)
            MainWindow.show() 
        
        